/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AcknowledgeEvent } from "./components/custom-alert/custom-alert";
export namespace Components {
    interface CustomAlert {
        "kind": "info" | "success" | "error";
        "text": string;
    }
    interface CustomTab {
        "active": boolean;
        "name": string;
    }
}
declare global {
    interface HTMLCustomAlertElement extends Components.CustomAlert, HTMLStencilElement {
    }
    var HTMLCustomAlertElement: {
        prototype: HTMLCustomAlertElement;
        new (): HTMLCustomAlertElement;
    };
    interface HTMLCustomTabElement extends Components.CustomTab, HTMLStencilElement {
    }
    var HTMLCustomTabElement: {
        prototype: HTMLCustomTabElement;
        new (): HTMLCustomTabElement;
    };
    interface HTMLElementTagNameMap {
        "custom-alert": HTMLCustomAlertElement;
        "custom-tab": HTMLCustomTabElement;
    }
}
declare namespace LocalJSX {
    interface CustomAlert {
        "kind"?: "info" | "success" | "error";
        "onAcknowledge"?: (event: CustomEvent<AcknowledgeEvent>) => void;
        "text"?: string;
    }
    interface CustomTab {
        "active"?: boolean;
        "name"?: string;
    }
    interface IntrinsicElements {
        "custom-alert": CustomAlert;
        "custom-tab": CustomTab;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-alert": LocalJSX.CustomAlert & JSXBase.HTMLAttributes<HTMLCustomAlertElement>;
            "custom-tab": LocalJSX.CustomTab & JSXBase.HTMLAttributes<HTMLCustomTabElement>;
        }
    }
}
