/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FormTest {
        "validator": string;
        "value": string;
    }
    interface InputTester {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TestComponent {
    }
}
declare global {
    interface HTMLFormTestElement extends Components.FormTest, HTMLStencilElement {
    }
    var HTMLFormTestElement: {
        prototype: HTMLFormTestElement;
        new (): HTMLFormTestElement;
    };
    interface HTMLInputTesterElement extends Components.InputTester, HTMLStencilElement {
    }
    var HTMLInputTesterElement: {
        prototype: HTMLInputTesterElement;
        new (): HTMLInputTesterElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "form-test": HTMLFormTestElement;
        "input-tester": HTMLInputTesterElement;
        "my-component": HTMLMyComponentElement;
        "test-component": HTMLTestComponentElement;
    }
}
declare namespace LocalJSX {
    interface FormTest {
        "validator"?: string;
        "value"?: string;
    }
    interface InputTester {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TestComponent {
        "onOnToggle"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "form-test": FormTest;
        "input-tester": InputTester;
        "my-component": MyComponent;
        "test-component": TestComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "form-test": LocalJSX.FormTest & JSXBase.HTMLAttributes<HTMLFormTestElement>;
            "input-tester": LocalJSX.InputTester & JSXBase.HTMLAttributes<HTMLInputTesterElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
        }
    }
}
